### ISSUE TITLE
sudo pip3 install CommandToDomoticz py-pushover-open-client requests

### ISSUE THREAD

**Issue by chrissb77** [Joe-houghton/IFTTTtoDomoticzUsingPushover#1]
Hi, 
I am quite new to this Rasperry/Linux/Domoticz thing so sorry if my question is trivial.
First of all, thanks for this plugin and the time you spent developing and sharing it.

One of the first steps is the command line: "sudo pip3 install CommandToDomoticz py-pushover-open-client requests"
I guess I have to replace "CommandToDomoticz" by something related to my install. But I am not sure what.
Thank you in advance for your help,
Chris

**Comment by Joe-houghton** [comment]
Hi Chris, no need to change anything, just follow the instructions.
Pip is a python install package and the arguments passed in to that (CommandToDomoticz, etc) are packages that will be installed.

**Comment by chrissb77** [comment]
Thanks, I manage to make it work now.
However, it seems like it works when I run the command "python3 /home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py"

But as soon as I disconnect (from the Pi via Putty) it doesn't work anymore.

**Comment by Joe-houghton** [comment]
Yes that would be right. 
If you add it to the startup file from the instructions, then reboot your pi. It will start as a background process and run indefinitely without you being connected.

**Comment by chrissb77** [comment]
Yes, I did add the line "python /home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py  > /home/pi/logs/pushover.log 2>&1"

Is there a way to make sure its running in the background after reboot?

**Comment by Joe-houghton** [comment]
Open the log
Nano /home/pi/logs/pushover.log

**Comment by Joe-houghton** [comment]
Out set up IFTTT and ask Google assistant to "Turn on xxxxx"

**Comment by chrissb77** [comment]
Here is what I get when I open the log. Am I not supposed to see the information about the requests which I started before the reboot (whuich worked) ?

_Traceback (most recent call last):
  File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 1, in <module>
    from pushover_open_client import *
ImportError: No module named pushover_open_client_

**Comment by Joe-houghton** [comment]
Did you get any errors when you did
"sudo pip3 install CommandToDomoticz py-pushover-open-client requests"

**Comment by chrissb77** [comment]
No, I don't think so. But at first I could not install it because I had an issue with pip3 apparently. I still moved forward with the next steps of the install. At first it did not work of course. Then I installed pip3 and CommandToDomoticz.
Maybe I should try to resinstall? If you think so as well, what would be the best way to de-install in a clean way?

**Comment by Joe-houghton** [comment]
Have you got it working yet?

**Comment by chrissb77** [comment]
Sorry for my late reply. I did not get it to work. Is there a way to check if it is actually loaded after a start of the pi?
